use_frameworks!

target 'SDWebImageLinkPlugin_Example' do
  platform :ios, '13.0'
  pod 'SDWebImageLinkPlugin', :path => '../'

  target 'SDWebImageLinkPlugin_Tests' do
    inherit! :search_paths

    
  end
end

target 'SDWebImageLinkPlugin_Example macOS' do
  platform :osx, '10.15'
  pod 'SDWebImageLinkPlugin', :path => '../'
end